# Generated by Django 5.2.4 on 2026-04-13 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('artforms', 'Artforms'), ('wildlife', 'Wildlife'), ('festivals', 'Festivals'), ('environment', 'Environment'), ('heritage', 'Heritage')], max_length=20)),
                ('class_level', models.CharField(choices=[('lower', 'Lower'), ('higher', 'Higher'), ('both', 'Both')], max_length=10)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='topics/')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoryPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('illustration', models.ImageField(upload_to='stories/')),
                ('text', models.TextField(blank=True)),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_panels', to='content.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ComicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('panel_image', models.ImageField(upload_to='comics/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_panels', to='content.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
