# Generated by Django 5.2.4 on 2026-04-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComicPanel',
        ),
    ]
