# Generated by Django 5.2.4 on 2026-04-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_comicpanel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='class_level',
            field=models.CharField(choices=[('lower', 'Lower'), ('higher', 'Higher'), ('both', 'Both')], help_text='Lower: shown in teacher projection sessions. Higher: shown in student academic study view. Both: available in both contexts.', max_length=10),
        ),
    ]
