# Generated by Django 5.2.4 on 2026-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_topic_class_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='sections',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
