# Generated by Django 5.2.4 on 2026-04-28 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('content', '0004_topic_sections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storypanel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stories/panels/'),
        ),
        migrations.AddField(
            model_name='storypanel',
            name='linked_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activities.activityquestion'),
        ),
        migrations.AddField(
            model_name='storypanel',
            name='panel_type',
            field=models.CharField(blank=True, choices=[('narration', 'Narration'), ('question', 'Question'), ('fact', 'Fun Fact'), ('activity', 'Activity Cue')], default='narration', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='storypanel',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='stories/audio/'),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='text',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('cover_image', models.ImageField(upload_to='stories/covers/')),
                ('character_name', models.CharField(max_length=50)),
                ('character_age', models.IntegerField()),
                ('character_avatar', models.CharField(max_length=10)),
                ('character_description', models.CharField(max_length=200)),
                ('story_type', models.CharField(choices=[('admin_original', 'Admin Original'), ('teacher_created', 'Teacher Created')], default='admin_original', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stories', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='content.topic')),
            ],
            options={
                'verbose_name_plural': 'Stories',
            },
        ),
        migrations.AddField(
            model_name='storypanel',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='content.story'),
        ),
        migrations.AlterUniqueTogether(
            name='storypanel',
            unique_together={('story', 'order')},
        ),
        migrations.RemoveField(
            model_name='storypanel',
            name='illustration',
        ),
        migrations.RemoveField(
            model_name='storypanel',
            name='topic',
        ),
    ]
