# Generated by Django 5.2.4 on 2026-04-28 07:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_storypanel_image_storypanel_linked_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypanel',
            name='text',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
    ]
