# Generated by Django 5.2.4 on 2026-04-28 07:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_storypanel_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypanel',
            name='image',
            field=models.ImageField(null=True, upload_to='stories/panels/'),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='panel_type',
            field=models.CharField(choices=[('narration', 'Narration'), ('question', 'Question'), ('fact', 'Fun Fact'), ('activity', 'Activity Cue')], default='narration', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='story',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='panels', to='content.story'),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='text',
            field=models.TextField(null=True, validators=[django.core.validators.MaxLengthValidator(250)]),
        ),
        migrations.AlterField(
            model_name='storypanel',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
