# Generated by Django 5.2.4 on 2026-04-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengesession',
            name='ghost_accuracy',
            field=models.FloatField(default=0.7),
        ),
        migrations.AddField(
            model_name='challengesession',
            name='ghost_name',
            field=models.CharField(default='EcoBot', max_length=50),
        ),
        migrations.AddField(
            model_name='challengesession',
            name='is_ghost',
            field=models.BooleanField(default=False),
        ),
    ]
