# Generated by Django 5.2.4 on 2026-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcqquestion',
            name='section_tag',
            field=models.CharField(blank=True, help_text='Tag this question to a specific section for targeted mini-quizzes after reading', max_length=50),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='attempt_metadata',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
