# Generated by Django 5.2.4 on 2026-02-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_classjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='class_obj',
            field=models.ForeignKey(blank=True, help_text="Link section to a specific class if it's class-specific content", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_sections', to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='section',
            name='is_general',
            field=models.BooleanField(default=False, help_text='General sections (Environment, Heritage, Cultural) are shown on home page and can only be edited by admin'),
        ),
        migrations.AddField(
            model_name='topic',
            name='is_general',
            field=models.BooleanField(default=False, help_text='General topics are visible to all students'),
        ),
    ]
