# Generated by Django 5.2.4 on 2026-02-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_section_class_obj_section_is_general_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject taught in this class (e.g., Mathematics, Science)', max_length=100),
        ),
    ]
