# Generated by Django 5.2.4 on 2026-02-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_class_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='studymaterial',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/audio/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='study_materials/images/'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='study_materials/video/'),
        ),
    ]
