# Generated by Django 5.2.4 on 2026-02-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_studymaterial_audio_studymaterial_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='student_class',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='student_class',
            field=models.ManyToManyField(blank=True, related_name='students', to='mainapp.class'),
        ),
    ]
