# Generated by Django 5.2.4 on 2026-02-24 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='profile_pictures/'),
        ),
    ]
