# Generated by Django 5.2.4 on 2026-02-28 08:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_userprofile_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Carbon Cycle, Biodiversity, Wildlife Conservation', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the concept')),
            ],
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', help_text='Beginner=Basics, Intermediate=Process&Details, Advanced=Case Studies', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='estimated_time',
            field=models.CharField(choices=[('short', 'Short (5 min)'), ('medium', 'Medium (10-15 min)'), ('long', 'Long (20 min)')], default='short', help_text='Short=5min, Medium=10-15min, Long=20min', max_length=20),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated summary of the material'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='content_text',
            field=models.TextField(help_text='Content with sections: Definition, Explanation, Example, Case Study, Summary'),
        ),
        migrations.AddField(
            model_name='studymaterial',
            name='concept_tags',
            field=models.ManyToManyField(blank=True, help_text='Tags for AI recommendations', related_name='study_materials', to='mainapp.concepttag'),
        ),
        migrations.CreateModel(
            name='MaterialAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('before_score', models.IntegerField(default=0)),
                ('after_score', models.IntegerField(default=0)),
                ('before_total', models.IntegerField(default=0)),
                ('after_total', models.IntegerField(default=0)),
                ('studied_at', models.DateTimeField(auto_now_add=True)),
                ('quiz_taken_at', models.DateTimeField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mainapp.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in seconds')),
                ('completion_status', models.BooleanField(default=False, help_text='Whether user completed viewing')),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='mainapp.studymaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_views', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_at'],
            },
        ),
    ]
