# Generated by Django 5.2.4 on 2026-03-04 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0016_concepttag_studymaterial_difficulty_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIGeneratedQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=500)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('order', models.IntegerField(default=0, help_text='Order of question in quiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=300)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='mainapp.aigeneratedquestion')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AIGeneratedQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title for the generated quiz', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('content_type', models.CharField(choices=[('general', 'General Content (Admin)'), ('class', 'Class-specific (Teacher)')], default='general', help_text='General content requires admin approval, class content uses teacher approval', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', help_text='Current approval status', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, help_text='When submitted for approval', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When reviewed/approved', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason if rejected')),
                ('used_count', models.IntegerField(default=0, help_text='Number of times this quiz was used')),
                ('approved_by', models.ForeignKey(blank=True, help_text='User who approved this quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quizzes', to=settings.AUTH_USER_MODEL)),
                ('class_obj', models.ForeignKey(blank=True, help_text='Class this quiz belongs to (for class-specific content)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_quizzes', to='mainapp.class')),
                ('generated_by', models.ForeignKey(help_text='User who generated this quiz', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_quizzes', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_quizzes', to='mainapp.section')),
                ('study_material', models.ForeignKey(help_text='Source study material used for generation', on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_quizzes', to='mainapp.studymaterial')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_generated_quizzes', to='mainapp.topic')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='mainapp.aigeneratedquiz'),
        ),
    ]
