# Generated by Django 5.2.4 on 2026-03-07 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_aigeneratedquestion_aigeneratedchoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Question has been reviewed and verified (not a generic placeholder)'),
        ),
        migrations.AddField(
            model_name='aigeneratedquestion',
            name='source_fact',
            field=models.CharField(blank=True, help_text='The specific fact or data point this question tests', max_length=200),
        ),
        migrations.AlterField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, help_text='Subject taught in this class', max_length=100),
        ),
    ]
