# Generated by Django 5.2.4 on 2026-03-08 14:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0018_aigeneratedquestion_is_verified_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='parent_topic',
            field=models.ForeignKey(blank=True, help_text='Parent topic in the Knowledge Bloom tree (leave empty for root topics)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='mainapp.topic'),
        ),
        migrations.CreateModel(
            name='TopicProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('quiz_score', models.IntegerField(default=0, help_text='Best quiz score for this topic')),
                ('quiz_total', models.IntegerField(default=0, help_text='Total questions in the quiz')),
                ('quiz_percentage', models.FloatField(default=0, help_text='Quiz score percentage')),
                ('study_time_minutes', models.IntegerField(default=0, help_text='Total time spent studying')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time student accessed this topic')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When topic was completed', null=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='mainapp.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_accessed'],
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
