# Generated by Django 5.2.4 on 2026-03-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0020_userprofile_xp_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='is_studied',
            field=models.BooleanField(default=False, help_text='User has explicitly marked the theory material as studied'),
        ),
    ]
