# Generated by Django 5.2.4 on 2026-03-15 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0021_topicprogress_is_studied'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectibleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('flora', 'Flora (Botanical)'), ('fauna', 'Fauna (Wildlife)'), ('folklore', 'Folklore (Legend)'), ('artifact', 'Artifact (History)')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='collectibles/')),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=20)),
                ('xp_value', models.IntegerField(default=50)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_xp', models.IntegerField(default=0)),
                ('max_xp', models.IntegerField(default=1000)),
                ('icon', models.CharField(default='fa-trophy', help_text='FontAwesome icon class', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0, help_text='Current daily login streak'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_date',
            field=models.DateField(blank=True, help_text='Last date user was active', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_streak',
            field=models.IntegerField(default=0, help_text='Highest daily login streak achieved'),
        ),
        migrations.CreateModel(
            name='ArtifactShard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('shard_index', models.IntegerField(help_text='Position of this shard in the reconstruction (e.g., 1 of 4)')),
                ('total_shards', models.IntegerField(default=4)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artifacts/shards/')),
                ('parent_artifact', models.ForeignKey(limit_choices_to={'category': 'artifact'}, on_delete=django.db.models.deletion.CASCADE, to='mainapp.collectibleitem')),
            ],
        ),
        migrations.CreateModel(
            name='UserLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_this_week', models.IntegerField(default=0)),
                ('rank_last_week', models.IntegerField(blank=True, null=True)),
                ('league', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.league')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='current_league', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserArtifactShard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('found_at', models.DateTimeField(auto_now_add=True)),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.artifactshard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifact_shards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'shard')},
            },
        ),
        migrations.CreateModel(
            name='UserCollectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.collectibleitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item')},
            },
        ),
    ]
