# Generated by Django 5.2.4 on 2026-03-15 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0022_collectibleitem_league_userprofile_current_streak_and_more'),
    ]

    operations = [
        # 1. Add fields first
        migrations.AddField(
            model_name='userartifactshard',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifact_shards', to='mainapp.userprofile'),
        ),
        migrations.AddField(
            model_name='usercollectible',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectibles', to='mainapp.userprofile'),
        ),
        migrations.AddField(
            model_name='userleague',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_league', to='mainapp.userprofile'),
        ),
        
        # 2. AlterUniqueTogether (now profile exists)
        migrations.AlterUniqueTogether(
            name='userartifactshard',
            unique_together={('profile', 'shard')},
        ),
        migrations.AlterUniqueTogether(
            name='usercollectible',
            unique_together={('profile', 'item')},
        ),
        
        # 3. Remove old fields
        migrations.RemoveField(
            model_name='userleague',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userartifactshard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usercollectible',
            name='user',
        ),
    ]
