# Generated by Django 5.2.4 on 2026-03-15 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0023_alter_userartifactshard_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('promotion', 'Promotion'), ('relegation', 'Relegation'), ('new_league', 'New League Joined')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('new_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mainapp.league')),
                ('old_league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mainapp.league')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_notifications', to='mainapp.userprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
