# Generated by Django 5.2.4 on 2026-03-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0025_story_storynode_storyprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='strikes_count',
            field=models.IntegerField(default=0, help_text='Number of wrong answers in this session'),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='total_time_limit',
            field=models.IntegerField(blank=True, help_text='Total time for the challenge in seconds (for Eco-Rush)', null=True),
        ),
        migrations.AddField(
            model_name='challengeattempt',
            name='total_xp_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='challengeattempt',
            name='challenge_type',
            field=models.CharField(choices=[('timed', 'Timed Challenge'), ('rapid', 'Rapid Fire'), ('adaptive', 'Adaptive Difficulty'), ('eco_rush', 'Eco-Rush (Timed)'), ('survival', 'Survival Mode (3 Strikes)'), ('sprint', 'Heritage Sprint')], default='timed', max_length=10),
        ),
    ]
