# Generated by Django 5.2.4 on 2026-03-28 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0026_challengeattempt_strikes_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComicPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_number', models.IntegerField(default=1)),
                ('character_name', models.CharField(help_text='Name of the character speaking', max_length=100)),
                ('dialogue', models.TextField(help_text='What the character is saying')),
                ('image', models.ImageField(blank=True, help_text='Character or scene visual', null=True, upload_to='comic/panels/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comic_panels', to='mainapp.topic')),
            ],
            options={
                'verbose_name': 'Comic Panel',
                'verbose_name_plural': 'Comic Panels',
                'ordering': ['panel_number'],
            },
        ),
        migrations.CreateModel(
            name='StoryScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_number', models.IntegerField(default=1)),
                ('text', models.TextField(help_text='Narrative text for this scene')),
                ('image', models.ImageField(blank=True, null=True, upload_to='story/scenes/')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='story_scenes', to='mainapp.topic')),
            ],
            options={
                'verbose_name': 'Story Scene',
                'verbose_name_plural': 'Story Scenes',
                'ordering': ['scene_number'],
            },
        ),
    ]
