# Generated by Django 5.2.4 on 2026-03-28 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_comicpanel_storyscene'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('coords', models.CharField(help_text='Image map coordinates (x1,y1,x2,y2 or poly coords)', max_length=500)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='mainapp.topic')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
    ]
