# Generated by Django 5.2.4 on 2026-03-30 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanel',
            name='character_type',
            field=models.CharField(choices=[('king', 'Ancient King (Gold)'), ('guide', 'Modern Student (Sleek)'), ('narrator', 'Narrator (Parchment)'), ('elder', 'Tribal Elder (Rustic)'), ('folk', 'Folk Legend (Visual)')], default='guide', max_length=20),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='is_fill_blank',
            field=models.BooleanField(default=False, help_text='Make part of the dialogue a quiz'),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='is_interactive',
            field=models.BooleanField(default=False, help_text="Enable 'Click to Reveal' interaction"),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='missing_word',
            field=models.CharField(blank=True, help_text="The correct word for 'Fill in the blank'", max_length=100),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='panel_type',
            field=models.CharField(choices=[('normal', 'Standard Panel'), ('wide', 'Wide Panel (Multi-column)'), ('tall', 'Tall Panel (Multi-row)'), ('hero', 'Hero Panel (Large)')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='comicpanel',
            name='sound_effect',
            field=models.CharField(blank=True, help_text="e.g., 'DUM DUM DUM' or 'SWOOSH'", max_length=100),
        ),
    ]
