# Generated by Django 5.2.4 on 2026-04-02 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_comicpanel_character_type_comicpanel_is_fill_blank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comicpanel',
            name='teacher_prompt',
            field=models.TextField(blank=True, help_text='Prompts for the teacher to ask students'),
        ),
        migrations.AddField(
            model_name='storyscene',
            name='teacher_prompt',
            field=models.TextField(blank=True, help_text="Prompts for the teacher to ask students (e.g., 'Why does rain fall here?')"),
        ),
    ]
