# Generated by Django 5.2.4 on 2026-04-10 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='associated_topic',
            field=models.ForeignKey(blank=True, help_text='Topic that unlocks this collectible on the progress map', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.topic'),
        ),
        migrations.CreateModel(
            name='MatchQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g., Match the Artform to the Region', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_quizzes', to='mainapp.topic')),
            ],
        ),
        migrations.CreateModel(
            name='MatchPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_item', models.CharField(help_text='e.g., Theyyam', max_length=150)),
                ('left_image', models.ImageField(blank=True, null=True, upload_to='match_quiz/')),
                ('right_item', models.CharField(help_text='e.g., North Malabar', max_length=150)),
                ('right_image', models.ImageField(blank=True, null=True, upload_to='match_quiz/')),
                ('order', models.IntegerField(default=0)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='mainapp.matchquiz')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
