# Generated by Django 5.2.4 on 2026-04-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_collectibleitem_associated_topic_matchquiz_matchpair'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='id_card_number',
            field=models.CharField(blank=True, help_text='Official Teacher Identification Number', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Whether this teacher has been approved by an administrator'),
        ),
    ]
