# Generated by Django 5.2.4 on 2026-04-20 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0033_teacher_id_card_number_teacher_is_approved'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComicPanel',
        ),
    ]
