# Generated by Django 5.2.4 on 2026-04-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0035_alter_class_unique_together_alter_class_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_lower_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='projection_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_classes_main', to='mainapp.topic'),
        ),
    ]
