# Generated by Django 5.2.4 on 2026-04-20 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_comicpanel'),
        ('mainapp', '0036_class_is_lower_class_class_projection_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='projection_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_classes_main', to='content.topic'),
        ),
    ]
