# Generated by Django 5.2.4 on 2026-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_alter_class_projection_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, help_text='Points used for higher class feature loop (performance, leaderboard, challenges)'),
        ),
    ]
