# Generated by Django 5.2.4 on 2026-04-30 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_storypanel_image_alter_storypanel_panel_type_and_more'),
        ('mainapp', '0039_dailytopicchallenge_dailychallengesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='projection_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_classes_main', to='content.story'),
        ),
    ]
