# Generated by Django 5.2.4 on 2026-05-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0040_class_projection_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='challenge_points',
            field=models.IntegerField(default=0, help_text='Points earned from daily challenges'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='challenge_streak',
            field=models.IntegerField(default=0, help_text='Current daily challenge streak'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_challenge_date',
            field=models.DateField(blank=True, help_text='Last date user completed a daily challenge', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='max_challenge_streak',
            field=models.IntegerField(default=0, help_text='Highest daily challenge streak achieved'),
        ),
    ]
