# Generated by Django 5.2.4 on 2026-05-02 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0041_userprofile_challenge_points_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dailytopicchallenge',
            unique_together=set(),
        ),
    ]
