# Generated by Django 5.2.4 on 2026-05-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0042_alter_dailytopicchallenge_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='folklore_topic',
            field=models.ForeignKey(blank=True, help_text='Specific folklore/myth topic for this district', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='folklore_districts', to='mainapp.topic'),
        ),
        migrations.AlterField(
            model_name='district',
            name='topic',
            field=models.ForeignKey(help_text='General content topic for this district', on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='mainapp.topic'),
        ),
    ]
