# Generated by Django 5.2.4 on 2026-05-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0043_district_folklore_topic_alter_district_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='activity_completed',
            field=models.BooleanField(default=False, help_text='User has successfully completed the interactive activity'),
        ),
    ]
