# Generated by Django 5.2.4 on 2026-05-05 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0044_topicprogress_activity_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='class_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenge_attempts', to='mainapp.class'),
        ),
        migrations.AddField(
            model_name='collectibleitem',
            name='icon',
            field=models.CharField(default='fa-gem', help_text='FontAwesome icon class', max_length=50),
        ),
    ]
