# Generated by Django 5.2.4 on 2026-05-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0045_challengeattempt_class_obj_collectibleitem_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='composite_marks',
            field=models.FloatField(default=0, help_text='Total marks (Auto + Manual)'),
        ),
        migrations.AddField(
            model_name='topicprogress',
            name='manual_marks',
            field=models.FloatField(default=0, help_text='Optional manual marks from teacher'),
        ),
    ]
