# Generated by Django 5.2.4 on 2026-05-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0046_topicprogress_composite_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicprogress',
            name='valuation_status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published')], default='pending_review', max_length=20),
        ),
    ]
