# Generated by Django 5.2.4 on 2026-04-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerclasssession',
            name='response_summary',
            field=models.JSONField(default=dict),
        ),
    ]
