# Generated by Django 5.2.4 on 2026-04-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0002_lowerclasssession_response_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerclasssession',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
