# Generated by Django 5.2.4 on 2026-04-18 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0003_lowerclasssession_current_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerclasssession',
            name='is_answer_revealed',
            field=models.BooleanField(default=False),
        ),
    ]
