# Generated by Django 5.2.4 on 2026-04-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_is_lower_class_class_projection_only_and_more'),
        ('learning_sessions', '0004_lowerclasssession_is_answer_revealed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowerclasssession',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='classes.class'),
        ),
    ]
