# Generated by Django 5.2.4 on 2026-04-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activityquestion_answer_and_more'),
        ('content', '0007_alter_storypanel_image_alter_storypanel_panel_type_and_more'),
        ('learning_sessions', '0005_lowerclasssession_class_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lowerclasssession',
            old_name='current_index',
            new_name='current_panel_index',
        ),
        migrations.RemoveField(
            model_name='lowerclasssession',
            name='activities_shown',
        ),
        migrations.RemoveField(
            model_name='lowerclasssession',
            name='is_answer_revealed',
        ),
        migrations.RemoveField(
            model_name='lowerclasssession',
            name='response_summary',
        ),
        migrations.AddField(
            model_name='lowerclasssession',
            name='stars_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lowerclasssession',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.story'),
        ),
        migrations.CreateModel(
            name='SessionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_level', models.CharField(choices=[('good', 'Most Got It'), ('mixed', 'Mixed Response'), ('struggled', 'Most Struggled')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('activity_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activityquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_responses', to='learning_sessions.lowerclasssession')),
            ],
        ),
    ]
