# Generated by Django 5.2.4 on 2026-04-30 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_sessions', '0006_rename_current_index_lowerclasssession_current_panel_index_and_more'),
        ('mainapp', '0040_class_projection_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lowerclasssession',
            name='class_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='mainapp.class'),
        ),
    ]
