# Generated by Django 5.2.4 on 2026-04-18 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_studymaterial_content_text_alter_studymaterial_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='is_lower_class',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='class',
            name='projection_only',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ManualStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_students', to='classes.class')),
            ],
        ),
    ]
