# Generated by Django 5.2.4 on 2026-04-20 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_class_is_lower_class_class_projection_only_and_more'),
        ('content', '0002_delete_comicpanel'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='projection_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_classes', to='content.topic'),
        ),
        migrations.AddField(
            model_name='class',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='manualstudent',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ManualStudentEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('good', 'Good'), ('mixed', 'Mixed'), ('struggled', 'Struggled')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_evaluations', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='classes.manualstudent')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.topic')),
            ],
            options={
                'ordering': ['-date_assigned'],
            },
        ),
    ]
