# Generated by Django 5.2.4 on 2026-04-20 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_class_projection_topic_class_subject_and_more'),
        ('mainapp', '0037_alter_class_projection_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualstudent',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_students', to='mainapp.class'),
        ),
        migrations.AlterField(
            model_name='manualstudentevaluation',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_evaluations', to='mainapp.class'),
        ),
        migrations.AlterField(
            model_name='studymaterial',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='mainapp.class'),
        ),
    ]
