# Generated by Django 5.2.4 on 2026-04-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('learning_sessions', '0002_lowerclasssession_response_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_level', models.CharField(choices=[('good', 'Most Got It'), ('mixed', 'Mixed Response'), ('struggled', 'Most Struggled')], max_length=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('activity_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activityquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='learning_sessions.lowerclasssession')),
            ],
        ),
    ]
