# Generated by Django 5.2.4 on 2026-04-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_studyprogress'),
        ('mainapp', '0037_alter_class_projection_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogress',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic'),
        ),
    ]
