# Generated by Django 5.2.4 on 2026-04-28 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_alter_studyprogress_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionResponse',
        ),
    ]
