# Generated by Django 5.2.4 on 2026-04-13 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('drag_drop', 'Drag and Drop'), ('image_pick', 'Pick the Image'), ('sequence', 'Put in Order'), ('tap_match', 'Match the Pairs')], max_length=20)),
                ('question_text', models.TextField()),
                ('items', models.JSONField()),
                ('answer', models.JSONField()),
                ('explanation', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='content.topic')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
