# Generated by Django 5.2.4 on 2026-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityquestion',
            name='answer',
            field=models.JSONField(help_text='Correct solution. Structure varies by type.'),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='items',
            field=models.JSONField(help_text='Structure varies by type. See examples in the admin.'),
        ),
        migrations.AlterField(
            model_name='activityquestion',
            name='question_type',
            field=models.CharField(choices=[('drag_drop', 'Drag and Drop'), ('sequence', 'Put in Order'), ('tap_match', 'Match the Pairs'), ('image_pick', 'Pick the Image')], max_length=20),
        ),
    ]
